// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6Y09AcCi0pa8CyWSRxrjsNVopgsUeZI',
    appId: '1:380668177994:web:0a72a4af64da6d6fa640b3',
    messagingSenderId: '380668177994',
    projectId: 'glucosync-925f3',
    authDomain: 'glucosync-925f3.firebaseapp.com',
    storageBucket: 'glucosync-925f3.firebasestorage.app',
    measurementId: 'G-NLCRXQQN0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHTCItTKqi2U3tcU5MxgJ7MVC76Q8IdM',
    appId: '1:380668177994:android:88a6e6a2a97ee5ada640b3',
    messagingSenderId: '380668177994',
    projectId: 'glucosync-925f3',
    storageBucket: 'glucosync-925f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-oy9Ka7uJOiMnUqMJfIMt_NrqB_-ldw',
    appId: '1:380668177994:ios:72fe0dc548d591b1a640b3',
    messagingSenderId: '380668177994',
    projectId: 'glucosync-925f3',
    storageBucket: 'glucosync-925f3.firebasestorage.app',
    iosBundleId: 'com.dms.dmsApp',
  );
}
